#############################################################################
# Makefile for building: Siepattu
# Generated by qmake (3.0) (Qt 5.1.0) on: Thu Apr 17 20:32:45 2014
# Project:  Siepattu.pro
# Template: aux
# Command: /usr/lib/qt5/bin/qmake QMAKE_CFLAGS_RELEASE=-O2\ -g\ -pipe\ -Wall\ -Wp,-D_FORTIFY_SOURCE=2\ -fexceptions\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -fmessage-length=0\ -march=armv7-a\ -mfloat-abi=hard\ -mfpu=vfpv3-d16\ -mno-thumb\ -Wno-psabi QMAKE_CFLAGS_DEBUG=-O2\ -g\ -pipe\ -Wall\ -Wp,-D_FORTIFY_SOURCE=2\ -fexceptions\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -fmessage-length=0\ -march=armv7-a\ -mfloat-abi=hard\ -mfpu=vfpv3-d16\ -mno-thumb\ -Wno-psabi QMAKE_CXXFLAGS_RELEASE=-O2\ -g\ -pipe\ -Wall\ -Wp,-D_FORTIFY_SOURCE=2\ -fexceptions\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -fmessage-length=0\ -march=armv7-a\ -mfloat-abi=hard\ -mfpu=vfpv3-d16\ -mno-thumb\ -Wno-psabi QMAKE_CXXFLAGS_DEBUG=-O2\ -g\ -pipe\ -Wall\ -Wp,-D_FORTIFY_SOURCE=2\ -fexceptions\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -fmessage-length=0\ -march=armv7-a\ -mfloat-abi=hard\ -mfpu=vfpv3-d16\ -mno-thumb\ -Wno-psabi QMAKE_STRIP=: PREFIX=/usr -o Makefile Siepattu.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -mno-thumb -Wno-psabi -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -mno-thumb -Wno-psabi -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt5/mkspecs/linux-g++ -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = :
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       =  
OBJECTS       = 
DIST          = /usr/share/qt5/mkspecs/features/spec_pre.prf \
		/usr/share/qt5/mkspecs/common/shell-unix.conf \
		/usr/share/qt5/mkspecs/common/unix.conf \
		/usr/share/qt5/mkspecs/common/linux.conf \
		/usr/share/qt5/mkspecs/common/gcc-base.conf \
		/usr/share/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt5/mkspecs/common/g++-base.conf \
		/usr/share/qt5/mkspecs/common/g++-unix.conf \
		/usr/share/qt5/mkspecs/qconfig.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_compositor.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_contacts.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_docgallery.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_feedback.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_organizer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versit.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/share/qt5/mkspecs/features/qt_functions.prf \
		/usr/share/qt5/mkspecs/features/qt_config.prf \
		/usr/share/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/share/qt5/mkspecs/features/spec_post.prf \
		/usr/share/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt5/mkspecs/features/default_pre.prf \
		/usr/share/qt5/mkspecs/features/unix/default_pre.prf \
		/usr/share/qt5/mkspecs/features/resolve_config.prf \
		/usr/share/qt5/mkspecs/features/default_post.prf \
		/usr/share/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt5/mkspecs/features/warn_on.prf \
		/usr/share/qt5/mkspecs/features/wayland-scanner.prf \
		/usr/share/qt5/mkspecs/features/testcase_targets.prf \
		/usr/share/qt5/mkspecs/features/exceptions.prf \
		/usr/share/qt5/mkspecs/features/yacc.prf \
		/usr/share/qt5/mkspecs/features/lex.prf \
		Siepattu.pro \
		Siepattu.pro
QMAKE_TARGET  = Siepattu
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Siepattu
TARGETA       = 
TARGETD       = 
TARGET0       = 
TARGET1       = 
TARGET2       = 


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ts engineering_english $(OBJECTS)  
	

Makefile: Siepattu.pro /usr/share/qt5/mkspecs/linux-g++/qmake.conf /usr/share/qt5/mkspecs/features/spec_pre.prf \
		/usr/share/qt5/mkspecs/common/shell-unix.conf \
		/usr/share/qt5/mkspecs/common/unix.conf \
		/usr/share/qt5/mkspecs/common/linux.conf \
		/usr/share/qt5/mkspecs/common/gcc-base.conf \
		/usr/share/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt5/mkspecs/common/g++-base.conf \
		/usr/share/qt5/mkspecs/common/g++-unix.conf \
		/usr/share/qt5/mkspecs/qconfig.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_compositor.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_contacts.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_docgallery.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_feedback.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_organizer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versit.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/share/qt5/mkspecs/features/qt_functions.prf \
		/usr/share/qt5/mkspecs/features/qt_config.prf \
		/usr/share/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/share/qt5/mkspecs/features/spec_post.prf \
		/usr/share/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt5/mkspecs/features/default_pre.prf \
		/usr/share/qt5/mkspecs/features/unix/default_pre.prf \
		/usr/share/qt5/mkspecs/features/resolve_config.prf \
		/usr/share/qt5/mkspecs/features/default_post.prf \
		/usr/share/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt5/mkspecs/features/warn_on.prf \
		/usr/share/qt5/mkspecs/features/wayland-scanner.prf \
		/usr/share/qt5/mkspecs/features/testcase_targets.prf \
		/usr/share/qt5/mkspecs/features/exceptions.prf \
		/usr/share/qt5/mkspecs/features/yacc.prf \
		/usr/share/qt5/mkspecs/features/lex.prf \
		Siepattu.pro
	$(QMAKE) QMAKE_CFLAGS_RELEASE=-O2\ -g\ -pipe\ -Wall\ -Wp,-D_FORTIFY_SOURCE=2\ -fexceptions\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -fmessage-length=0\ -march=armv7-a\ -mfloat-abi=hard\ -mfpu=vfpv3-d16\ -mno-thumb\ -Wno-psabi QMAKE_CFLAGS_DEBUG=-O2\ -g\ -pipe\ -Wall\ -Wp,-D_FORTIFY_SOURCE=2\ -fexceptions\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -fmessage-length=0\ -march=armv7-a\ -mfloat-abi=hard\ -mfpu=vfpv3-d16\ -mno-thumb\ -Wno-psabi QMAKE_CXXFLAGS_RELEASE=-O2\ -g\ -pipe\ -Wall\ -Wp,-D_FORTIFY_SOURCE=2\ -fexceptions\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -fmessage-length=0\ -march=armv7-a\ -mfloat-abi=hard\ -mfpu=vfpv3-d16\ -mno-thumb\ -Wno-psabi QMAKE_CXXFLAGS_DEBUG=-O2\ -g\ -pipe\ -Wall\ -Wp,-D_FORTIFY_SOURCE=2\ -fexceptions\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -fmessage-length=0\ -march=armv7-a\ -mfloat-abi=hard\ -mfpu=vfpv3-d16\ -mno-thumb\ -Wno-psabi QMAKE_STRIP=: PREFIX=/usr -o Makefile Siepattu.pro
/usr/share/qt5/mkspecs/features/spec_pre.prf:
/usr/share/qt5/mkspecs/common/shell-unix.conf:
/usr/share/qt5/mkspecs/common/unix.conf:
/usr/share/qt5/mkspecs/common/linux.conf:
/usr/share/qt5/mkspecs/common/gcc-base.conf:
/usr/share/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt5/mkspecs/common/g++-base.conf:
/usr/share/qt5/mkspecs/common/g++-unix.conf:
/usr/share/qt5/mkspecs/qconfig.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_compositor.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_contacts.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_declarative.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_docgallery.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_feedback.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_organizer.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_serviceframework.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_versit.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_versitorganizer.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/share/qt5/mkspecs/features/qt_functions.prf:
/usr/share/qt5/mkspecs/features/qt_config.prf:
/usr/share/qt5/mkspecs/linux-g++/qmake.conf:
/usr/share/qt5/mkspecs/features/spec_post.prf:
/usr/share/qt5/mkspecs/features/exclusive_builds.prf:
/usr/share/qt5/mkspecs/features/default_pre.prf:
/usr/share/qt5/mkspecs/features/unix/default_pre.prf:
/usr/share/qt5/mkspecs/features/resolve_config.prf:
/usr/share/qt5/mkspecs/features/default_post.prf:
/usr/share/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt5/mkspecs/features/warn_on.prf:
/usr/share/qt5/mkspecs/features/wayland-scanner.prf:
/usr/share/qt5/mkspecs/features/testcase_targets.prf:
/usr/share/qt5/mkspecs/features/exceptions.prf:
/usr/share/qt5/mkspecs/features/yacc.prf:
/usr/share/qt5/mkspecs/features/lex.prf:
Siepattu.pro:
qmake: FORCE
	@$(QMAKE) QMAKE_CFLAGS_RELEASE=-O2\ -g\ -pipe\ -Wall\ -Wp,-D_FORTIFY_SOURCE=2\ -fexceptions\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -fmessage-length=0\ -march=armv7-a\ -mfloat-abi=hard\ -mfpu=vfpv3-d16\ -mno-thumb\ -Wno-psabi QMAKE_CFLAGS_DEBUG=-O2\ -g\ -pipe\ -Wall\ -Wp,-D_FORTIFY_SOURCE=2\ -fexceptions\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -fmessage-length=0\ -march=armv7-a\ -mfloat-abi=hard\ -mfpu=vfpv3-d16\ -mno-thumb\ -Wno-psabi QMAKE_CXXFLAGS_RELEASE=-O2\ -g\ -pipe\ -Wall\ -Wp,-D_FORTIFY_SOURCE=2\ -fexceptions\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -fmessage-length=0\ -march=armv7-a\ -mfloat-abi=hard\ -mfpu=vfpv3-d16\ -mno-thumb\ -Wno-psabi QMAKE_CXXFLAGS_DEBUG=-O2\ -g\ -pipe\ -Wall\ -Wp,-D_FORTIFY_SOURCE=2\ -fexceptions\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -fmessage-length=0\ -march=armv7-a\ -mfloat-abi=hard\ -mfpu=vfpv3-d16\ -mno-thumb\ -Wno-psabi QMAKE_STRIP=: PREFIX=/usr -o Makefile Siepattu.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/Siepattu1.0.0 || mkdir -p .tmp/Siepattu1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Siepattu1.0.0/ && (cd `dirname .tmp/Siepattu1.0.0` && $(TAR) Siepattu1.0.0.tar Siepattu1.0.0 && $(COMPRESS) Siepattu1.0.0.tar) && $(MOVE) `dirname .tmp/Siepattu1.0.0`/Siepattu1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Siepattu1.0.0


clean:compiler_clean 
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


ts:
	lupdate /home/mersdk/share/Downloads/Jolla-TOH-Developer-Kit/templates/Siepattu/ -ts /home/mersdk/share/Downloads/Jolla-TOH-Developer-Kit/templates/Siepattu/translations/Siepattu.ts

engineering_english: ts
	lrelease -idbased /home/mersdk/share/Downloads/Jolla-TOH-Developer-Kit/templates/Siepattu/translations/Siepattu.ts -qm /home/mersdk/share/Downloads/Jolla-TOH-Developer-Kit/templates/Siepattu/translations/Siepattu_eng_en.qm

check: first

compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_qtwayland-client-header_make_all:
compiler_qtwayland-client-header_clean:
compiler_qtwayland-client-code_make_all:
compiler_qtwayland-client-code_clean:
compiler_qtwayland-server-header_make_all:
compiler_qtwayland-server-header_clean:
compiler_qtwayland-server-code_make_all:
compiler_qtwayland-server-code_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

####### Install

install_ambience: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/ambience/Siepattu || mkdir -p $(INSTALL_ROOT)/usr/share/ambience/Siepattu
	-$(INSTALL_PROGRAM) /home/mersdk/share/Downloads/Jolla-TOH-Developer-Kit/templates/Siepattu/Siepattu.ambience $(INSTALL_ROOT)/usr/share/ambience/Siepattu/
	-: $(INSTALL_ROOT)/usr/share/ambience/Siepattu/Siepattu.ambience
	-$(INSTALL_PROGRAM) /home/mersdk/share/Downloads/Jolla-TOH-Developer-Kit/templates/Siepattu/sounds.index $(INSTALL_ROOT)/usr/share/ambience/Siepattu/
	-: $(INSTALL_ROOT)/usr/share/ambience/Siepattu/sounds.index

uninstall_ambience: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/ambience/Siepattu/sounds.index
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/ambience/Siepattu/Siepattu.ambience
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/ambience/Siepattu/ 


install_images: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/ambience/Siepattu/images || mkdir -p $(INSTALL_ROOT)/usr/share/ambience/Siepattu/images
	-$(INSTALL_FILE) /home/mersdk/share/Downloads/Jolla-TOH-Developer-Kit/templates/Siepattu/images/Siepattu.jpg $(INSTALL_ROOT)/usr/share/ambience/Siepattu/images/

uninstall_images: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/ambience/Siepattu/images/Siepattu.jpg
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/ambience/Siepattu/images/ 


install_sounds: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/ambience/Siepattu/sounds || mkdir -p $(INSTALL_ROOT)/usr/share/ambience/Siepattu/sounds
	-$(INSTALL_FILE) /home/mersdk/share/Downloads/Jolla-TOH-Developer-Kit/templates/Siepattu/sounds/Siepattu-Ringtone.wav $(INSTALL_ROOT)/usr/share/ambience/Siepattu/sounds/

uninstall_sounds: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/ambience/Siepattu/sounds/Siepattu-Ringtone.wav
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/ambience/Siepattu/sounds/ 


install_ts_install: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/translations/source || mkdir -p $(INSTALL_ROOT)/usr/share/translations/source
	-$(INSTALL_FILE) /home/mersdk/share/Downloads/Jolla-TOH-Developer-Kit/templates/Siepattu/translations/Siepattu.ts $(INSTALL_ROOT)/usr/share/translations/source/

uninstall_ts_install: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/translations/source/Siepattu.ts
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/translations/source/ 


install_engineering_english_install: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/translations || mkdir -p $(INSTALL_ROOT)/usr/share/translations
	-$(INSTALL_FILE) /home/mersdk/share/Downloads/Jolla-TOH-Developer-Kit/templates/Siepattu/translations/Siepattu_eng_en.qm $(INSTALL_ROOT)/usr/share/translations/

uninstall_engineering_english_install: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/translations/Siepattu_eng_en.qm
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/translations/ 


install:  install_ambience install_images install_sounds install_ts_install install_engineering_english_install  FORCE

uninstall: uninstall_ambience uninstall_images uninstall_sounds uninstall_ts_install uninstall_engineering_english_install   FORCE

FORCE:

